### ISSUE TITLE
Help with ember htmlbars

### ISSUE THREAD

**Issue by mxrlkn** [mattma/gulp-htmlbars#1]
Hi. I'm trying to to switch to htmlbars from handlebars and I'm having a hard time figuring out how to do it.

I have just copied your example from the readme.

This is my gulp task:

```
gulp.task('templates', function () {
  gulp.src(src + "templates/*.hbs")
    .pipe(htmlbars({
            isHTMLBars: true,
            templateCompiler: require("./bower_components/ember/ember-template-compiler")
        }))
  .pipe(wrap({
      deps:         ['exports'],          // dependency array
      params:       ['__exports__'],        // params for callback
      moduleRoot:   'src/templates/'
    }))
    .pipe(concat('templates.js'))
    .pipe(gulp.dest(src + 'assets/js'))
    .pipe(gulp.dest(dist + 'assets/js'));
});
```

But in the console I get `Uncaught SyntaxError: Unexpected reserved word`

And it points to the first line here:

```
return export default Ember.HTMLBars.template((function() {
  return {
    isHTMLBars: true,
    blockParams: 0,
    cachedFragment: null,
    hasRendered: false,
```

I'm running ember 1.10.0 and ember-data 1.0.0-beta.15.

I'm quite new to all this compiling so bear with me. Thanks.

**Comment by mattma** [comment]
This is not a bug. The goal of this plugin is to transform the `hbs` HTMLBars template into browser compatible javascript run-time code. 

If you are looking for the full solution, please check out my Project [Ember Rocks](https://github.com/mattma/ember-rocks). That is exactly what you are looking for. So do not spend your time to re-invent the wheel. I have done that for you.
