### ISSUE TITLE
Confused, is this ...

### ISSUE THREAD

**Issue by blaasvaer** [mattma/gulp-htmlbars#3]
... part of gulp-handlebars now?

And if, can I use it without using Ember?

**Comment by mattma** [comment]
@blaasvaer This plugin was made two years ago and it works for ember 1.x. I do not believe it is compatible with the latest Glimmer 2 or Handlebars at all. Please, follow the guide from the Ember core team for the plugins recommendation.

**Comment by blaasvaer** [comment]
OK, shame about the name though, as it says nothing about being specifically ember related.
